apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.deployment.serviceName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.deployment.serviceName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.deployment.serviceName }}
