apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.serviceName }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.deployment.port }}
      targetPort: {{ .Values.deployment.port }}
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}