apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapiapp.fullname" . }}
  labels:
    {{- include "webapiapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webapiapp.selectorLabels" . | nindent 4 }}
